sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk

before_script:
- composer install
- curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh
- source $HOME/.nvm/nvm.sh
- nvm install v10.13.0
- node --version
- npm install && npm start
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
- composer test

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
